### ISSUE TITLE
property_tree fails to compile with BOOST_NO_TYPEID/BOOST_NO_RTTI defined

### ISSUE THREAD

**Issue by clevijoki** [boostorg/property_tree#33]
typeid() is used in some exception macros in detail/ptree_implementation.hpp

**Comment by andreasschultes** [comment]
https://github.com/boostorg/property_tree/pull/20
https://github.com/boostorg/property_tree/pull/21

**Comment by ashtum** [comment]
Addressed in https://github.com/boostorg/property_tree/commit/3b7c3ccb6bf5438c1a2d1b663762d69760a6386d.
