### ISSUE TITLE
property_tree/detail/file_parser_error.hpp does not #include <sstream>

### ISSUE THREAD

**Issue by urnathan** [boostorg/property_tree#99]
This was discovered when enabling clang implicit modules (and by implication will affect C++20 header-units).  property_tree/detail/file_parser_error.hpp uses stringstream without #including <sstream>, and therefore is not self contained.  Fixed thusly:
```
--- c/1.77.0/src/boost_1_77_0/boost/property_tree/detail/file_parser_error.hpp
+++ w/1.77.0/src/boost_1_77_0/boost/property_tree/detail/file_parser_error.hpp
@@ -12,6 +12,7 @@
 
 #include <boost/property_tree/ptree.hpp>
 #include <string>
+#include <sstream>
 
 namespace boost { namespace property_tree
 {
```

**Comment by madmongo1** [comment]
Thank you.

**Comment by ashtum** [comment]
Addressed in https://github.com/boostorg/property_tree/pull/112.
